spring.application.name=vehicle_maintenance_scheduler
server.port=8080

# Logging Configurations
logging.level.org.springframework.web=INFO

# JSON Formatting
spring.jackson.serialization.indent_output=true
